#!/usr/bin/env python3
"""pine_factory_to_wiki.py — flat pinescript_factory → llmwiki pines graph.

Generates:
  wiki/pines/scripts/<stem>.md
  wiki/pines/categories/<tag>.md
  wiki/pines/pines-map.md

Factory `.pine` files are SoT — do NOT duplicate into wiki/raw/ (raw is for
external/experimental sources; analysis ingest copies one script when needed).

Also patches wiki/index.md Pines section.

Run:
  python3 "${WIKI_PATH}/hermes/scripts/pine_factory_to_wiki.py"
"""
from __future__ import annotations

import datetime
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve()
WIKI = HERE.parents[2] / "wiki"
DEV = HERE.parents[3]
FACTORY = DEV / "MantisAlgo" / "pinescript_factory"
TODAY = datetime.date.today().isoformat()
MARK = "> ⚙️ AUTO-GENERATED by `hermes/scripts/pine_factory_to_wiki.py` — 손으로 고치지 마세요. 지식은 [[mantisalgo]]·분석 페이지에."

# Import taxonomy from factory_saver
sys.path.insert(0, str(DEV / "MantisAlgo" / "mantis"))
from factory_saver import CATEGORIES, parse_tags_from_code  # noqa: E402

_TITLE_RE = re.compile(r"//\s*Title:\s*(.+)", re.IGNORECASE)
_KIND_RE = re.compile(r"//\s*Kind:\s*(indicator|strategy)", re.IGNORECASE)
_CONCEPT_RE = re.compile(r"//\s*Concept:\s*(.+)", re.IGNORECASE)
_TIER_RE = re.compile(r"//\s*Tier:\s*(.+)", re.IGNORECASE)
_SKU_RE = re.compile(r"SKU-?(\d+)", re.IGNORECASE)


def slug_tag(tag: str) -> str:
    return tag.lower().replace("_", "-")


def script_slug(stem: str) -> str:
    return stem.lower().replace("_", "-")


def cat_link(tag: str) -> str:
    """Path-qualified to avoid colliding with wiki/modules/<id>.md basenames."""
    return f"[[pines/categories/{slug_tag(tag)}|{tag}]]"


def script_link(stem: str, title=None) -> str:
    slug = script_slug(stem)
    if title:
        return f"[[pines/scripts/{slug}|{title}]]"
    return f"[[pines/scripts/{slug}]]"


def fm(tags: str) -> str:
    return (
        f"---\ntags: {tags}\nupdated: {TODAY}\n"
        f'sources: ["MantisAlgo/pinescript_factory/"]\n---'
    )


def scan() -> list[dict]:
    rows = []
    for macro, kind_hint in (("1_Indicators", "indicator"), ("2_Strategies", "strategy")):
        d = FACTORY / macro
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.pine")):
            text = p.read_text(encoding="utf-8")
            title_m = _TITLE_RE.search(text)
            kind_m = _KIND_RE.search(text)
            concept_m = _CONCEPT_RE.search(text)
            tier_m = _TIER_RE.search(text)
            tags = parse_tags_from_code(text)
            sku_m = _SKU_RE.search(p.stem) or (title_m and _SKU_RE.search(title_m.group(1)))
            rows.append({
                "stem": p.stem,
                "path": p,
                "rel": str(p.relative_to(DEV / "MantisAlgo")),
                "title": title_m.group(1).strip() if title_m else p.stem.replace("_", " "),
                "kind": (kind_m.group(1).lower() if kind_m else kind_hint),
                "tags": tags,
                "concept": concept_m.group(1).strip() if concept_m else "",
                "tier": tier_m.group(1).strip() if tier_m else "",
                "sku": f"SKU-{int(sku_m.group(1)):02d}" if sku_m else "",
                "lines": len(text.splitlines()),
            })
    return rows


def write_script_page(row: dict, out_dir: Path) -> None:
    tag_links = " · ".join(cat_link(t) for t in row["tags"]) or "(없음)"
    lines = [
        fm(f"[pine-script, mantisalgo, {row['kind']}]"),
        "",
        f"# {row['title']}",
        MARK,
        "",
        f"- kind: **{row['kind']}** · file: `{row['rel']}` · lines: {row['lines']}",
    ]
    if row["sku"]:
        lines.append(f"- SKU: [[{row['sku']}]]")
    lines.append(f"- tags: {tag_links}")
    if row["concept"]:
        lines.append(f"- concept: {row['concept']}")
    if row["tier"]:
        lines.append(f"- tier: {row['tier']}")
    lines += [
        "",
        "## 🔗 연결",
        f"{tag_links} · [[pines/pines-map]] · [[mantisalgo]]",
        "",
    ]
    (out_dir / f"{script_slug(row['stem'])}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_category_page(tag: str, scripts: list[dict], out_dir: Path) -> None:
    slug = slug_tag(tag)
    links = " · ".join(script_link(r["stem"], r["title"]) for r in scripts) or "(아직 없음)"
    body = "\n".join([
        fm("[pine-category, mantisalgo]"),
        "",
        f"# {tag}",
        MARK,
        "",
        "> Mantis 택소노미 태그. 스크립트는 폴더가 아니라 `// Tags:`로 여기 연결된다.",
        "",
        f"- 소속 스크립트 {len(scripts)}개: {links}",
        "",
        "## 🔗 연결",
        "[[pines/pines-map]] · [[mantisalgo]]",
        "",
    ])
    (out_dir / f"{slug}.md").write_text(body, encoding="utf-8")


def write_map(rows: list[dict], by_tag: dict[str, list[dict]], out: Path) -> None:
    ind = [r for r in rows if r["kind"] == "indicator"]
    strat = [r for r in rows if r["kind"] == "strategy"]

    lines = [
        fm("[pine-script, mantisalgo, hub]"),
        "",
        "# Pines Map (파인 스크립트 지도)",
        MARK,
        "",
        f"스크립트 {len(rows)}개 · indicator {len(ind)} · strategy {len(strat)} · 사용 중 태그 {len(by_tag)}종",
        "",
        "## Indicators",
        "- " + " · ".join(script_link(r["stem"], r["title"]) for r in ind),
        "",
        "## Strategies",
        "- " + " · ".join(script_link(r["stem"], r["title"]) for r in strat),
        "",
        "## Categories (다대다)",
    ]
    for tag in sorted(by_tag.keys()):
        scripts = by_tag[tag]
        lines.append(
            f"- {cat_link(tag)} ({len(scripts)}): "
            + " · ".join(script_link(r["stem"], r["title"]) for r in scripts)
        )
    unused = [t for t in CATEGORIES if t not in by_tag]
    if unused:
        lines += ["", "## Taxonomy (미사용 태그)", "- " + " · ".join(cat_link(t) for t in unused)]
    lines += ["", "[[mantisalgo]] · [[mantisalgo-sku-catalog]] · [[modules-map]]", ""]
    out.write_text("\n".join(lines), encoding="utf-8")


def patch_index() -> None:
    index = WIKI / "index.md"
    text = index.read_text(encoding="utf-8")
    section = (
        "\n## Pines (auto-generated — `pine_factory_to_wiki.py`)\n\n"
        "- [[pines/pines-map]] — 파인 스크립트 지도 (indicator/strategy + Tags 다대다)\n"
    )
    if "[[pines/pines-map]]" in text:
        return
    # insert before Modules & SKUs if present
    needle = "## Modules & SKUs"
    if needle in text:
        text = text.replace(needle, section.lstrip("\n") + "\n" + needle)
    else:
        text += section
    index.write_text(text, encoding="utf-8")


def main() -> int:
    if not FACTORY.is_dir():
        print(f"Factory not found: {FACTORY}", file=sys.stderr)
        return 1
    rows = scan()
    sdir = WIKI / "pines" / "scripts"
    cdir = WIKI / "pines" / "categories"
    sdir.mkdir(parents=True, exist_ok=True)
    cdir.mkdir(parents=True, exist_ok=True)

    by_tag: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        write_script_page(r, sdir)
        for t in r["tags"]:
            by_tag[t].append(r)

    # category pages: used tags + full taxonomy stubs
    all_tags = set(CATEGORIES) | set(by_tag)
    for tag in sorted(all_tags):
        write_category_page(tag, by_tag.get(tag, []), cdir)

    write_map(rows, dict(by_tag), WIKI / "pines" / "pines-map.md")
    patch_index()
    print(f"scripts={len(rows)} categories={len(all_tags)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
