#!/usr/bin/env python3
"""registry_to_wiki.py — MantisAlgo registry.json → Obsidian wiki pages.

Generates auto-maintained pages so the Obsidian graph shows which modules
each SKU uses and how modules depend on each other.

  wiki/modules/<id>.md      one page per module
  wiki/skus/<SKU-XX>.md     one page per product SKU
  wiki/modules/modules-map.md  hub page (family → modules, kind → modules), linked from index

Modules also carry a `kind` field (2026-07-17): ui (chart display layer) |
logic (factory analysis/signal — used by both indicators and strategies) |
infra (assembly plumbing). See entities/mantisalgo-module-registry.md.

Run after any registry/SKU change:
  python3 "${WIKI_PATH}/hermes/scripts/registry_to_wiki.py"

Pages are AUTO-GENERATED — do not hand-edit (they get overwritten).
Hand-written knowledge belongs in entities/mantisalgo-*.md pages.
"""
import json, datetime
from pathlib import Path

HERE = Path(__file__).resolve()
# hermes/scripts → llmwiki root (parents[2]); wiki lives beside hermes/
WIKI = HERE.parents[2] / "wiki"
DEV = HERE.parents[3]          # sibling parent (.../dev) for MantisAlgo registry
REG = DEV / "MantisAlgo" / "config" / "module_registry" / "registry.json"
TODAY = datetime.date.today().isoformat()
MARK = "> ⚙️ AUTO-GENERATED by `hermes/scripts/registry_to_wiki.py` — 손으로 고치지 마세요. 지식은 [[mantisalgo-module-registry]]에."

def fm(tags):
    return f"---\ntags: {tags}\nupdated: {TODAY}\nsources: [\"MantisAlgo/config/module_registry/registry.json\"]\n---"

def main():
    d = json.loads(REG.read_text())
    mods = {m["id"]: m for m in d["modules"]}
    skus = d.get("product_skus", {})

    # reverse map: module -> SKUs using it
    def feat_list(info):
        f = info.get("features", [])
        if f == "all":
            # SKU-08: live + sku_ship (default True) — smoke-only modules stay out
            return [
                m["id"] for m in d["modules"]
                if m.get("status", "live") == "live" and m.get("sku_ship", True)
            ]
        return f if isinstance(f, list) else []

    used_by = {}
    for sku, info in skus.items():
        fl = feat_list(info)
        for f in fl:
            used_by.setdefault(f, []).append(sku)
    # reverse deps: module -> modules that depend on it
    dependents = {}
    for m in d["modules"]:
        for dep in m.get("depends_on", []):
            dependents.setdefault(dep, []).append(m["id"])

    mdir = WIKI / "modules"; sdir = WIKI / "skus"
    mdir.mkdir(exist_ok=True); sdir.mkdir(exist_ok=True)

    for m in d["modules"]:
        mid = m["id"]
        kind = m.get("kind", "logic")
        lines = [fm(f"[module, mantisalgo, {m['family']}, kind/{kind}]"), "", f"# {mid}", MARK, "",
                 f"- family: **{m['family']}** · kind: **{kind}** · status: {m['status']} · est_lines: {m['est_lines']}"]
        if m.get("description"):
            lines.append(f"- {m['description']}")
        deps = m.get("depends_on", [])
        if deps:
            lines.append("- depends on: " + " ".join(f"[[{x}]]" for x in deps))
        if dependents.get(mid):
            lines.append("- depended on by: " + " ".join(f"[[{x}]]" for x in dependents[mid]))
        if used_by.get(mid):
            lines.append("- used in: " + " ".join(f"[[{x}]]" for x in used_by[mid]))
        lines += ["", "[[modules-map]] · [[mantisalgo-module-registry]]", ""]
        (mdir / f"{mid}.md").write_text("\n".join(lines))

    # generate for every SKU json in the folder (registry mapping may lag behind)
    sku_dir = DEV / "MantisAlgo" / "config" / "product_skus"
    all_skus = {f.stem: json.loads(f.read_text()) for f in sorted(sku_dir.glob("SKU-*.json"))}
    unmapped = [s for s in all_skus if s not in skus]

    for sku, extra in all_skus.items():
        info = skus.get(sku, {})
        lines = [fm("[sku, mantisalgo]"), "", f"# {sku} — {info.get('name', extra.get('name',''))}", MARK, ""]
        if extra.get("description"):
            lines.append(f"> {extra['description']}")
            lines.append("")
        if extra.get("tier"):
            lines.append(f"- tier: {extra['tier']} · architecture: {extra.get('architecture_hint','-')}")
        feats = feat_list(info) if info else []
        if info.get("features") == "all":
            smoke = sum(1 for m in d["modules"] if not m.get("sku_ship", True))
            lines.append(
                f"- 사용 모듈 {len(feats)}개: `features: \"all\"` (sku_ship:true live만"
                + (f"; smoke-only {smoke}종 제외" if smoke else "")
                + ") → [[modules-map]]"
            )
        elif feats:
            lines.append(f"- 사용 모듈 {len(feats)}개: " + " ".join(f"[[{x}]]" for x in feats))
        else:
            lines.append("- ⚠️ 상충: registry.json `product_skus`에 모듈 매핑 없음 — 레지스트리 미등록 SKU (module-developer 확인 필요)")
        if extra.get("extends"):
            lines.append(f"- extends: [[{extra['extends']}]]")
        lines += ["", "[[mantisalgo-sku-catalog]] · [[modules-map]]", ""]
        (sdir / f"{sku}.md").write_text("\n".join(lines))

    # hub page: family -> modules, kind -> modules
    fams = {}
    kinds = {}
    for m in d["modules"]:
        fams.setdefault(m["family"], []).append(m["id"])
        kinds.setdefault(m.get("kind", "logic"), []).append(m["id"])
    lines = [fm("[module, mantisalgo, hub]"), "", "# Modules Map (모듈 지도)", MARK, "",
             f"모듈 {d['total_modules']}개 · live {d['live_count']} · planned {d['planned_count']} · SKU {len(all_skus)}개 (레지스트리 미매핑: {', '.join(unmapped) or '없음'})", "",
             "## SKU", "- " + " · ".join(f"[[{s}]]" for s in sorted(all_skus)), "",
             "## Kind (1급 분류 — 2026-07-17)",
             "판매 첫인상을 담당하는 표현층(ui)과, 그 밑에서 돌아가는 분석/시그널(logic), 조립 기반(infra)을 분리.", ""]
    for kind in ("ui", "logic", "infra"):
        ids = kinds.get(kind, [])
        lines.append(f"### {kind} ({len(ids)})")
        lines.append("- " + " · ".join(f"[[{x}]]" for x in sorted(ids)))
        lines.append("")
    lines.append("## Family")
    lines.append("")
    for fam in sorted(fams):
        lines.append(f"### {fam} ({len(fams[fam])})")
        lines.append("- " + " · ".join(f"[[{x}]]" for x in sorted(fams[fam])))
        lines.append("")
    (mdir / "modules-map.md").write_text("\n".join(lines))
    print(f"OK: {len(mods)} module pages, {len(all_skus)} SKU pages, 1 hub → {WIKI}/modules, /skus")

if __name__ == "__main__":
    main()
